const fakeArray = [
	{
		id: 0,
		time: 'Jan 17, 2019, 8:00:05 AM',
		symbol: 'ETHUSD',
		execType: 'Trade',
		side: 'Buy',
		execQty: 100,
		execPrice: 120.85,
		value: 0.0012,
		feeRate: 0.0750,
		feePaid: 0.00000090,
	},
	{
		id: 1,
		time: 'Jan 17, 2019, 5:20:05 AM',
		symbol: 'ETHUSD',
		execType: 'Trade',
		side: 'Buy',
		execQty: 5,
		execPrice: 120.20,
		value: -0.0012,
		feeRate: 0.0750,
		feePaid: 0.00000090,
	},
	{
		id: 2,
		time: 'Jan 17, 2019, 4:00:0 AM',
		symbol: 'XBTUSD',
		execType: 'Trade',
		side: 'Buy',
		execQty: 100,
		execPrice: 3598.0,
		value: -0.002,
		feeRate: -0.0136,
		feePaid: 0.00000004,
	},
	{
		id: 3,
		time: 'Jan 17, 2019, 4:00:0 AM',
		symbol: 'ETHUSD',
		execType: 'Trade',
		side: 'Sell',
		execQty: 55,
		execPrice: 3598.0,
		value: -0.002,
		feeRate: -0.0136,
		feePaid: 0.00000004,
	},
	{
		id: 4,
		time: 'Jan 17, 2019, 4:00:0 AM',
		symbol: 'ETHUSD',
		execType: 'Trade',
		side: 'Buy',
		execQty: 5,
		execPrice: 3598.0,
		value: -0.002,
		feeRate: -0.0136,
		feePaid: 0.00000004,
	},
	{
		id: 5,
		time: 'Jan 17, 2019, 4:00:0 AM',
		symbol: 'XBTUSD',
		execType: 'Trade',
		side: 'Sell',
		execQty: 50,
		execPrice: 3598.0,
		value: -0.002,
		feeRate: -0.0136,
		feePaid: 0.00000004,
	},
	{
		id: 6,
		time: 'Jan 17, 2019, 4:00:0 AM',
		symbol: 'XBTUSD',
		execType: 'Trade',
		side: 'Sell',
		execQty: 50,
		execPrice: 3598.0,
		value: -0.002,
		feeRate: -0.0136,
		feePaid: 0.00000004,
	},
	{
		id: 7,
		time: 'Jan 17, 2019, 4:00:0 AM',
		symbol: 'ETHUSD',
		execType: 'Trade',
		side: 'Sell',
		execQty: 55,
		execPrice: 3598.0,
		value: -0.002,
		feeRate: -0.0136,
		feePaid: 0.00000004,
	},
];



//////////////////////////////////////////
//////////////////////////////////////////
//////////////////////////////////////////



export const apiArray = [
  {
    "orderID": "d6c7d322-252c-8249-7320-f75910a2c6ff",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "XBTUSD",
    "side": "Buy",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 3886,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Filled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 1000,
    "avgPx": 3886,
    "multiLegReportingType": "SingleSecurity",
    "text": "Amended price: Amend from www.bitmex.com\nSubmission from www.bitmex.com",
    "transactTime": "2019-02-18T19:35:02.339Z",
    "timestamp": "2019-02-18T19:37:54.355Z"
  },
  {
    "orderID": "9f8b4369-005e-5ce8-5986-1c49a16b8f3f",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Sell",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 142.15,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Filled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 1000,
    "avgPx": 142.15,
    "multiLegReportingType": "SingleSecurity",
    "text": "Submission from www.bitmex.com",
    "transactTime": "2019-02-18T22:43:50.036Z",
    "timestamp": "2019-02-18T22:43:50.036Z"
  },
  {
    "orderID": "f82449f0-a25f-8b07-c738-8fcf7442e895",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Buy",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 146.2,
    "displayQty": null,
    "stopPx": 146.15,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Stop",
    "timeInForce": "ImmediateOrCancel",
    "execInst": "Close,LastPrice",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Filled",
    "triggered": "StopOrderTriggered",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 1000,
    "avgPx": 146.2,
    "multiLegReportingType": "SingleSecurity",
    "text": "Triggered: Order stop price reached\nSubmission from www.bitmex.com",
    "transactTime": "2019-02-19T00:05:13.678Z",
    "timestamp": "2019-02-19T00:05:13.678Z"
  },
  {
    "orderID": "30e61f03-fc34-e5e6-f9b5-af855d0206c7",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Buy",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 140.75,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "ReduceOnly",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Canceled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 0,
    "avgPx": null,
    "multiLegReportingType": "SingleSecurity",
    "text": "Canceled: Order had execInst of Close or ReduceOnly but open buy orders exceed current position of -1000\nSubmission from www.bitmex.com",
    "transactTime": "2019-02-18T22:57:44.699Z",
    "timestamp": "2019-02-19T00:05:13.678Z"
  },
  {
    "orderID": "3fcb1500-9be9-dd29-429a-b17bc9803663",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "XBTUSD",
    "side": "Sell",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 3925,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "ReduceOnly",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Filled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 1000,
    "avgPx": 3925,
    "multiLegReportingType": "SingleSecurity",
    "text": "Submission from www.bitmex.com",
    "transactTime": "2019-02-18T19:40:01.940Z",
    "timestamp": "2019-02-19T00:38:20.313Z"
  },
  {
    "orderID": "9be8e02e-9626-4396-c352-ec6b89398f58",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Buy",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 148.9,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "ReduceOnly",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Canceled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 0,
    "avgPx": null,
    "multiLegReportingType": "SingleSecurity",
    "text": "Canceled: Order had execInst of Close or ReduceOnly and side of Buy but current position is 0\nSubmission from www.bitmex.com",
    "transactTime": "2019-02-19T00:59:26.716Z",
    "timestamp": "2019-02-19T00:59:26.716Z"
  },
  {
    "orderID": "08dd2196-216d-5a29-055d-9aea898d7df0",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "XBTUSD",
    "side": "Sell",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": null,
    "displayQty": null,
    "stopPx": 3766,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Stop",
    "timeInForce": "ImmediateOrCancel",
    "execInst": "Close,LastPrice",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Canceled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 0,
    "avgPx": null,
    "multiLegReportingType": "SingleSecurity",
    "text": "Canceled: Cancel from www.bitmex.com\nSubmission from www.bitmex.com",
    "transactTime": "2019-02-18T19:32:07.252Z",
    "timestamp": "2019-02-19T00:59:35.128Z"
  },
  {
    "orderID": "47b1dd06-15dd-5aa4-4005-c90cb96027ab",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Buy",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 148.75,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "ReduceOnly",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Canceled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 0,
    "avgPx": null,
    "multiLegReportingType": "SingleSecurity",
    "text": "Canceled: Order had execInst of Close or ReduceOnly and side of Buy but current position is 0\nSubmission from www.bitmex.com",
    "transactTime": "2019-02-19T00:59:58.239Z",
    "timestamp": "2019-02-19T00:59:58.239Z"
  },
  {
    "orderID": "7efd676a-89c4-7f08-6f26-1d28ab92b0c8",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Buy",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 148.75,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Filled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 1000,
    "avgPx": 148.75,
    "multiLegReportingType": "SingleSecurity",
    "text": "Submission from www.bitmex.com",
    "transactTime": "2019-02-19T01:00:08.407Z",
    "timestamp": "2019-02-19T01:00:27.134Z"
  },
  {
    "orderID": "c6c4f7f1-deb7-d17b-6b5f-37e1f0456795",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Sell",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 150.25,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "ReduceOnly",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "Canceled",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 0,
    "simpleCumQty": null,
    "cumQty": 0,
    "avgPx": null,
    "multiLegReportingType": "SingleSecurity",
    "text": "Canceled: Cancel from www.bitmex.com\nSubmission from www.bitmex.com",
    "transactTime": "2019-02-19T01:01:16.774Z",
    "timestamp": "2019-02-19T01:01:59.968Z"
  },
  {
    "orderID": "7ee30bcb-82a3-9dd1-1be3-eebb5887dc6a",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Sell",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": null,
    "displayQty": null,
    "stopPx": 144.3,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Stop",
    "timeInForce": "ImmediateOrCancel",
    "execInst": "Close,LastPrice",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "New",
    "triggered": "",
    "workingIndicator": false,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 1000,
    "simpleCumQty": null,
    "cumQty": 0,
    "avgPx": null,
    "multiLegReportingType": "SingleSecurity",
    "text": "Submission from www.bitmex.com",
    "transactTime": "2019-02-19T01:01:44.884Z",
    "timestamp": "2019-02-19T01:01:44.884Z"
  },
  {
    "orderID": "28105698-8935-7430-4035-8375b43210fe",
    "clOrdID": "",
    "clOrdLinkID": "",
    "account": 793053,
    "symbol": "ETHUSD",
    "side": "Sell",
    "simpleOrderQty": null,
    "orderQty": 1000,
    "price": 150.25,
    "displayQty": null,
    "stopPx": null,
    "pegOffsetValue": null,
    "pegPriceType": "",
    "currency": "USD",
    "settlCurrency": "XBt",
    "ordType": "Limit",
    "timeInForce": "GoodTillCancel",
    "execInst": "ReduceOnly",
    "contingencyType": "",
    "exDestination": "XBME",
    "ordStatus": "New",
    "triggered": "",
    "workingIndicator": true,
    "ordRejReason": "",
    "simpleLeavesQty": null,
    "leavesQty": 1000,
    "simpleCumQty": null,
    "cumQty": 0,
    "avgPx": null,
    "multiLegReportingType": "SingleSecurity",
    "text": "Submission from www.bitmex.com",
    "transactTime": "2019-02-19T01:02:27.827Z",
    "timestamp": "2019-02-19T01:02:27.827Z"
  }
]

export default fakeArray;